### ISSUE TITLE
Characteristic value not updates.

### ISSUE THREAD

**Issue by veer9002** [SiliconLabs/EFRConnect-ios#6]
Hi!
I am facing issues in write request and steps that I followed to write the characteristics are as follow:

Step 1: I connected the device from the browser screen. 
Step 2: I wrote the characteristic in ASCII field. e.g., 321 and last value was 123456
Step 3: Now I read the same characteristic which was updated recently and I got the result as e.g., 321456. So here, my updated value is appended by its prior value. Hence result is incorrect. 
Step 4: Then I tried disconnecting it and connect and then I read the characteristic. Hence, result is same i.e., 321456. So, is not updated.

This happens certain time not regularly.

**Comment by silabs-TiagoM** [comment]
This doesn't seem like a problem, it is normal behavior when using static length characteristics. 

If you are writing less bytes than what the characteristic holds, the value of those bytes which are not overwritten is kept. 

You can declare your characteristic as variable length instead of static or write all 0's to the characteristic before writing the new value, whichever suits best to your application.

**Comment by veer9002** [comment]
Can you please elaborate by giving the example.

**Comment by silabs-TiagoM** [comment]
What you described above is an example of how it's supposed to work.

**Comment by veer9002** [comment]
So I need to do it at BLE's end or iOS mobile app end?

**Comment by silabs-TiagoM** [comment]
A github issue is not the place to clarify on how BLE works. I recommend that you create a post on your community: https://community.silabs.com/s/

**Comment by veer9002** [comment]
OK. Thank you
